WebApplication1/Models/Track.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models {
    public class Track {
        [Key]
        public string Key { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Background { get; set; }
        public string Coverart { get; set; }
        public string Genres { get; set; } 
        //рядки будуть розділятись /n
        public string Text { get; set; }
        public string Footer { get; set; }
        public string Caption { get; set; }
        public string Uri { get; set; }
        public int PlaylistId { get; set; }

        public Dictionary<string, string> lang = new Dictionary<string, string>
        {
            { "af", "Afrikaans" },
            { "sq", "Albanian" },
            { "am", "Amharic" },
            { "ar", "Arabic" },
            { "hy", "Armenian" },
            { "az", "Azerbaijani" },
            { "eu", "Basque" },
            { "be", "Belarusian" },
            { "bn", "Bengali" },
            { "bs", "Bosnian" },
            { "bg", "Bulgarian" },
            { "ca", "Catalan" },
            { "ceb", "Cebuano" },
            { "ny", "Chichewa" },
            { "zh-CN", "Chinese (Simplified)" },
            { "zh-TW", "Chinese (Traditional)" },
            { "co", "Corsican" },
            { "hr", "Croatian" },
            { "cs", "Czech" },
            { "da", "Danish" },
            { "nl", "Dutch" },
            { "en", "English"},
            { "eo", "Esperanto" },
            { "et", "Estonian" },
            { "tl", "Filipino" },
            { "fi", "Finnish" },
            { "fr", "French" },
            { "fy", "Frisian" },
            { "gl", "Galician" },
            { "ka", "Georgian" },
            { "de", "German" },
            { "el", "Greek"},
            { "gu", "Gujarati" },
            { "ht", "Haitian Creole" },
            { "ha", "Hausa" },
            { "haw", "Hawaiian" },
            { "he", "Hebrew" },
            { "iw", "Hebrew" },
            { "hi", "Hindi" },
            { "hmn", "Hmong" },
            { "hu", "Hungarian" },
            { "is", "Icelandic" },
            { "ig", "Igbo" },
            { "id", "Indonesian" },
            { "ga", "Irish" },
            { "it", "Italian" },
            { "ja", "Japanese" },
            { "jw", "Javanese" },
            { "kn", "Kannada" },
            { "kk", "Kazakh" },
            { "km", "Khmer" },
            { "rw", "Kinyarwanda" },
            { "ko", "Korean" },
            { "ku", "Kurdish (Kurmanji)" },
            { "ky", "Kyrgyz" },
            { "lo", "Lao" },
            { "la", "Latin" },
            { "lv", "Latvian" },
            { "lt", "Lithuanian" },
            { "lb", "Luxembourgish" },
            { "mk", "Macedonian" },
            { "mg", "Malagasy" },
            { "ms", "Malay" },
            { "ml", "Malayalam" },
            { "mt", "Maltese" },
            { "mi", "Maori" },
            { "mr", "Marathi" },
            { "mn", "Mongolian" },
            { "my", "Myanmar (Burmese)" },
            { "ne", "Nepali" },
            { "no", "Norwegian" },
            { "or", "Odia (Oriya)" },
            { "ps", "Pashto" },
            { "fa", "Persian" },
            { "pl", "Polish" },
            { "pt", "Portuguese" },
            { "pa", "Punjabi" },
            { "ro", "Romanian" },
            { "ru", "Russian" },
            { "sm", "Samoan" },
            { "gd", "Scots Gaelic" },
            { "sr", "Serbian" },
            { "st", "Sesotho" },
            { "sn", "Shona" },
            { "sd", "Sindhi" },
            { "si", "Sinhala" },
            { "sk", "Slovak" },
            { "sl", "Slovenian" },
            { "so", "Somali" },
            { "es", "Spanish" },
            { "su", "Sundanese" },
            { "sw", "Swahili" },
            { "sv", "Swedish" },
            { "tg", "Tajik" },
            { "ta", "Tamil" },
            { "tt", "Tatar" },
            { "te", "Telugu" },
            { "th", "Thai" },
            { "tr", "Turkish" },
            { "uk", "Ukrainian" },
            { "ur", "Urdu" },
            { "ug", "Uyghur" },
            { "uz", "Uzbek" },
            { "vi", "Vietnamese" },
            { "cy", "Welsh" },
            { "xh", "Xhosa" },
            { "yi", "Yiddish" },
            { "yo", "Yoruba" },
            { "zu", "Zulu" }
        };

        public Track() {}
        public Track(string key, string title, string subtitle, string background, string coverart, string genres, string text, string footer, string caption, string uri) {
            Key = key;
            Title = title;
            Subtitle = subtitle;
            Background = background;
            Coverart = coverart;
            Genres = genres;
            Text = text;
            Footer = footer;
            Caption = caption;
            Uri = uri;
        }        
    }
}
/*
{
    "key": "590804188",
    "title": "Like A Villain",
    "subtitle": "Bad Omens",
    "background": "https://is2-ssl.mzstatic.com/image/thumb/Music126/v4/fc/f8/08/fcf808aa-fc48-5b99-0734-f3eea9eb52a2/pr_source.png/800x800cc.jpg",
    "coverart": "https://is4-ssl.mzstatic.com/image/thumb/Music126/v4/03/49/0f/03490fc4-2ea2-61f3-6bbf-5382ea002087/810016765424.jpg/400x400cc.jpg",
    "genres": "Metal",
    "text": [
                "Look into my face, then look again",
                "We are not the same, we're different",
                "To tell your tales and fables, you couldn't wait",
                "You need a new clean slate without the dents",
                "A place to put your pain, your consequence",
                "When you look into the mirror, are you even there?",
                "",
                "I don't wanna know all your secrets 'cause I'll tell",
                "It's hard enough being alone with myself",
                "I don't know how long I'll be holding on",
                "I know you tried your hardest, I know that you meant well",
                "But you pushed me to the edge, and I slipped and then I fell",
                "I don't know how long I'll be holding on",
                "",
                "So write a brand new page, then write again",
                "I know your act is staged yet you pretend",
                "All while you're turning tables with missing legs",
                "I think you've overstayed your welcome in",
                "So go the fuck away, don't come again",
                "I'll see your face in the fire and burn it out",
                "",
                "I don't wanna know all your secrets 'cause I'll tell",
                "It's hard enough being alone with myself",
                "I don't know how long I'll be holding on",
                "I know you tried your hardest, I know that you meant well",
                "But you pushed me to the edge, and I slipped and then I fell",
                "I don't know how long I'll be holding on",
                "",
                "Like a villain, I couldn't be",
                "I didn't need it, it needed me",
                "Like a villain, I couldn't be",
                "I didn't need it, it needed me",
                "",
                "I didn't need it, it needed me",
                "",
                "I don't wanna know all your secrets 'cause I'll tell",
                "It's hard enough being alone with myself",
                "I don't know how long I'll be holding on",
                "I know you tried your hardest, I know that you meant well",
                "But you pushed me to the edge, and I slipped, and then I fell",
                "I don't know how long I'll be holding on",
                "",
                "I didn't need it, it needed me"
            ],
    "footer": "Writer(s): Joakim Oskar Patrick Karlsson, Noah Sebastian Davis\nLyrics powered by www.musixmatch.com",
    "caption": "BAD OMENS - Like A Villain (Official Music Video)",
    "url": "https://i.ytimg.com/vi/Aibxit_PpAg/maxresdefault.jpg",
    "uri": "https://youtu.be/Aibxit_PpAg?autoplay=1"
}
*/

WebApplication1/Controllers/TracksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TracksController : Controller
    {
        private readonly WebApplication1Context _context;

        public TracksController(WebApplication1Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString)
        {            
            var tracks = from t in _context.Track
                 select t;

            if (!string.IsNullOrEmpty(searchString))
            {
                tracks = tracks.Where(s => s.Title!.Contains(searchString) || s.Subtitle!.Contains(searchString));
            }
            return View(await tracks.ToListAsync());             
        }

        public IActionResult Artists() 
        {
            var tracksDist = _context.Track
                .GroupBy(t => t.Subtitle)
                .Select(g => g.First())
                .ToList();

            Constants.tracksCount = _context.Track
                .GroupBy(t => t.Subtitle)
                .Select(g => g.Count())
                .ToList();

            return View(tracksDist);
        }
        
        public async Task<IActionResult> ArtistDetails(string id) 
        {
            var tracks = _context.Track.Where(s => s.Subtitle == id);
            return View(await tracks.ToListAsync());
        }

        public IActionResult Add(string Key, string Title, string Subtitle, string Background, string Coverart, string Genres, string Text, string Footer, string Caption, string Uri) 
        {
            Track track = new
                (
                    Key,
                    Title,
                    Subtitle,
                    Background,
                    Coverart,
                    Genres,
                    Text,
                    Footer,
                    Caption,
                    Uri
                );
            return View(track);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Key,Title,Subtitle,Background,Coverart,Genres,Text,Footer,Caption,Uri")] Track track) {
            if (ModelState.IsValid)
            {
                _context.Add(track);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(track);            
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Track == null)
            {
                return NotFound();
            }

            var track = await _context.Track
                .FirstOrDefaultAsync(m => m.Key == id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        public async Task<IActionResult> GetLink(string id) {
            HttpClient client = new HttpClient();           
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"{Constants.baseurlDownload}/dl?id={id}"),
                Headers =
                {
                    { "X-RapidAPI-Host", Constants.hostDownload },
                    { "X-RapidAPI-Key", Constants.apikey },
                },
            };
            DownloadLink result;
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var content = response.Content.ReadAsStringAsync().Result;
                result = JsonConvert.DeserializeObject<DownloadLink>(content);
            }
            Process.Start(new ProcessStartInfo
            {
                FileName = result.Link,
                UseShellExecute = true
            });
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddToPlaylist(string id) {
            Constants.trackId = id;
            return View("~/Views/Playlists/Menu.cshtml", await _context.Playlist.ToListAsync());
        }     

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Track == null)
            {
                return NotFound();
            }

            var track = await _context.Track.FindAsync(id);
            if (track == null)
            {
                return NotFound();
            }
            return View(track);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Key,Title,Subtitle,Background,Coverart,Genres,Text,Footer,Caption,Uri")] Track track)
        {
            if (id != track.Key) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(track);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrackExists(track.Key)) return NotFound();
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(track);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Track == null) return NotFound();

            var track = await _context.Track
                .FirstOrDefaultAsync(m => m.Key == id);
            if (track == null) return NotFound();

            return View(track);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Track == null) return Problem("Entity set 'WebApplication1Context.Track'  is null.");

            var track = await _context.Track.FindAsync(id);
            if (track != null) _context.Track.Remove(track);

            var playlist = await _context.Playlist.FirstOrDefaultAsync(m => m.Id == track.PlaylistId);
            if (playlist != null)
            {
                if (playlist.TracksCount > 1)
                    playlist.TracksCount -= 1;
                playlist.TracksCount = 0;  
            }
                        
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }       
       
        private bool TrackExists(string id)
        {
          return _context.Track.Any(e => e.Key == id);
        }
       
    }
}

WebApplication1/Controllers/TranslationController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication1.Models;

namespace WebApplication1.Controllers {
    public class TranslationController : Controller {
        public async Task<IActionResult> Index(string text, string tl, string key) {

            HttpClient client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"{Constants.baseurlTranslate}/translate?text={text}&tl={tl}"),
                Headers =
                {
                    { "X-RapidAPI-Host", Constants.hostTranslate },
                    { "X-RapidAPI-Key", Constants.apikey },
                },
            };
            Translation result;
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var content = response.Content.ReadAsStringAsync().Result;
                result = JsonConvert.DeserializeObject<Translation>(content);
            }
            Constants.tranText = result;
            return RedirectToAction("Details", "Tracks", new {id = key});
        }
    }
}
/*
"af":"Afrikaans"
"am":"Amharic"
"ar":"Arabic"
"auto":"Detect Language"
"az":"Azerbaijani"
"be":"Belarusian"
"bg":"Bulgarian"
"bn":"Bengali"
"bs":"Bosnian"
"ca":"Catalan"
"ceb":"Cebuano"
"co":"Corsican"
"cs":"Czech"
"cy":"Welsh"
"da":"Danish"
"de":"German"
"el":"Greek"
"en":"English"
"eo":"Esperanto"
"es":"Spanish"
"et":"Estonian"
"eu":"Basque"
"fa":"Persian"
"fi":"Finnish"
"fr":"French"
"fy":"Frisian"
"ga":"Irish"
"gd":"Scots Gaelic"
"gl":"Galician"
"gu":"Gujarati"
"ha":"Hausa"
"haw":"Hawaiian"
"he":"Hebrew"
"hi":"Hindi"
"hmn":"Hmong"
"hr":"Croatian"
"ht":"Haitian Creole"
"hu":"Hungarian"
"hy":"Armenian"
"id":"Indonesian"
"ig":"Igbo"
"is":"Icelandic"
"it":"Italian"
"iw":"Hebrew"
"ja":"Japanese"
"jw":"Javanese"
"ka":"Georgian"
"kk":"Kazakh"
"km":"Khmer"
"kn":"Kannada"
"ko":"Korean"
"ku":"Kurdish (Kurmanji)"
"ky":"Kyrgyz"
"la":"Latin"
"lb":"Luxembourgish"
"lo":"Lao"
"lt":"Lithuanian"
"lv":"Latvian"
"mg":"Malagasy"
"mi":"Maori"
"mk":"Macedonian"
"ml":"Malayalam"
"mn":"Mongolian"
"mr":"Marathi"
"ms":"Malay"
"mt":"Maltese"
"my":"Myanmar (Burmese)"
"ne":"Nepali"
"nl":"Dutch"
"no":"Norwegian"
"ny":"Chichewa"
"pa":"Punjabi"
"pl":"Polish"
"ps":"Pashto"
"pt":"Portuguese"
"ro":"Romanian"
"ru":"Russian"
"sd":"Sindhi"
"si":"Sinhala"
"sk":"Slovak"
"sl":"Slovenian"
"sm":"Samoan"
"sn":"Shona"
"so":"Somali"
"sq":"Albanian"
"sr":"Serbian"
"st":"Sesotho"
"su":"Sundanese"
"sv":"Swedish"
"sw":"Swahili"
"ta":"Tamil"
"te":"Telugu"
"tg":"Tajik"
"th":"Thai"
"tl":"Filipino"
"tr":"Turkish"
"uk":"Ukrainian"
"ur":"Urdu"
"uz":"Uzbek"
"vi":"Vietnamese"
"xh":"Xhosa"
"yi":"Yiddish"
"yo":"Yoruba"
"zh-CN":"Chinese (Simplified)"
"zh-TW":"Chinese (Traditional)"
"zu":"Zulu"
 */

WebApplication1/Views/Tracks/Add.cshtml
@model WebApplication1.Models.Track

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Track</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Key" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtitle" class="control-label"></label>
                <input asp-for="Subtitle" class="form-control" />
                <span asp-validation-for="Subtitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Background" class="control-label"></label>
                <input asp-for="Background" class="form-control" />
                <span asp-validation-for="Background" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coverart" class="control-label"></label>
                <input asp-for="Coverart" class="form-control" />
                <span asp-validation-for="Coverart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genres" class="control-label"></label>
                <input asp-for="Genres" class="form-control" />
                <span asp-validation-for="Genres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Footer" class="control-label"></label>
                <input asp-for="Footer" class="form-control" />
                <span asp-validation-for="Footer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Caption" class="control-label"></label>
                <input asp-for="Caption" class="form-control" />
                <span asp-validation-for="Caption" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uri" class="control-label"></label>
                <input asp-for="Uri" class="form-control" />
                <span asp-validation-for="Uri" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Tracks/ArtistDetails.cshtml
@model IEnumerable<WebApplication1.Models.Track>

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Artist — @Html.DisplayFor(model => model.FirstOrDefault().Subtitle)</h4>
    <hr />
</div>

<ul>
    @foreach(var item in Model)
    {
        Uri uri = new Uri(item.Uri);
        string videoid = uri.Segments.Last();
    <li class="sgLi"> 
        <div>
            <ul class="item">
                <li>
                    <img src="@item.Coverart" alt="Track Image" width="230" height="230" class="trackImg"/>
                </li>
                <li>
                    <div class="hideblock">
                        <br/>
                        <div>@Html.DisplayFor(modelItem => item.Title) — @Html.DisplayFor(modelItem => item.Subtitle)</div>  
                        <p>@Html.DisplayFor(modelItem => item.Genres)</p>
                        <a asp-action="GetLink" asp-route-id="@videoid" title="Download Link">
                            <img src="https://icon-library.com/images/download-icon-black/download-icon-black-10.jpg" width="25" height="25">
                        </a> 
                        <a asp-action="Edit" asp-route-id="@item.Key" title="Edit">
                            <img src="https://www.seekpng.com/png/full/202-2022672_edit-comments-edit-icon-png-circle.png" width="25" height="25">
                        </a>
                        <a asp-action="Details" asp-route-id="@item.Key" title="Details">
                            <img src="https://www.shareicon.net/data/512x512/2015/11/07/668200_info_512x512.png" width="25" height="25">
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Key" title="Delete">
                            <img src="https://cdn-icons-png.flaticon.com/512/70/70091.png" width="25" height="25">
                        </a>
                        <a asp-action="AddToPlaylist" asp-route-id="@item.Key" title="Add to Playlist">
                            <img src="https://static.thenounproject.com/png/1676791-200.png" width="25" height="25">
                        </a>
                    </div>
                    <img src="https://cyrilmagic.com/wp-content/uploads/2020/05/PLAY-BUTTON-WHITE.png" class="button" loading="lazy">
                    <iframe loading="lazy" title="Music audio" width="350" height="170" src="@item.Uri?modestbranding=1&showinfo=0&fs=0" frameborder="0"></iframe>
                </li>
            </ul>
        </div>
    </li>
    }
</ul>

<div>
    <a asp-action="Artists">Back to List</a>
</div>

WebApplication1/Views/Tracks/Artists.cshtml
@model IEnumerable<WebApplication1.Models.Track>

@{
    ViewData["Title"] = "Artists";
}

<h1>@ViewData["Title"]</h1>

<p>The list of artists with saved songs</p>

<ul class="SG">
    @{
        int i = 0;
    }
    @foreach(var item in Model)
    {
    <li class="sgLi"> 
        <div>
            <ul class="item">
                <li>
                    <img src="@item.Background" alt="Artist Image" width="230" height="230"/>
                </li>
                <li>
                    <div>@Html.DisplayFor(modelItem => item.Subtitle)</div>
                </li>
                <li>
                    @{
                        <p>Tracks count: @Constants.tracksCount[i].ToString()</p>
                        i++;
                    }
                </li>
                <li>
                    <a asp-action="ArtistDetails" asp-route-id="@item.Subtitle" title="Details">
                        <img src="https://www.shareicon.net/data/512x512/2015/11/07/668200_info_512x512.png" width="25" height="25">
                    </a>              
                </li>
            </ul>
        </div>
    </li>
    }
</ul>

WebApplication1/Views/Tracks/Details.cshtml
@model WebApplication1.Models.Track

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Track</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Background)            
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Background" alt="Artist Image" width="230" height="230" style="border:3px solid white;"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Coverart)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Coverart" alt="Track Image" width="230" height="230" style="border:3px solid white;"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @{
                var lyrics = Model.Text.Split(".");
                foreach(string l in lyrics)
                {
                    <div>@l.ToString()</div>
                }
            }
        </dd>        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Footer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Footer)
        </dd>
        <dt class = "col-sm-2">
            Translation
        </dt>
        <dd class = "col-sm-10">
            <form asp-controller="Translation" asp-action="Index">
                <input type="hidden" asp-for="Key" />
                <input type="hidden" asp-for="Text" />
                <input list="tl" name="tl">
                <datalist id="tl">
                    @foreach(var lang in Model.lang)
                    {
                        <option value="@lang.Key">@lang.Value</option>
                    }
                </datalist> 
                <input type="submit" value="Translate" />
            </form> 
            @if(Constants.tranText != null)
            {
                var lyricsTr = Constants.tranText.data.translation.Split(".");
                foreach(string l in lyricsTr)
                {
                    <div>@l.ToString()</div>
                }
                Constants.tranText = null;
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Caption)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Caption)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uri)
        </dt>
        <dd class = "col-sm-10">                 
            <iframe style="border:3px solid white;" loading="lazy" title="Music video" width="640" height="360" src="@Model.Uri" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Key">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model?.Key">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>