WebApplication1/Controllers/SearchController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication1.Models;

namespace WebApplication1.Controllers {
    public class SearchController : Controller {

        public async Task<ActionResult> Index(string searchString) 
        {
            HttpClient client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"{Constants.baseurl}/search?term={searchString}&limit=5"),
                Headers =
                {
                    { "X-RapidAPI-Host", Constants.host },
                    { "X-RapidAPI-Key", Constants.extraApikey },
                },
            };
            Shazam result;
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var content = response.Content.ReadAsStringAsync().Result;
                result = JsonConvert.DeserializeObject<Shazam>(content);
            }
            return View(result); 
        }

        public async Task<ActionResult> Details(string id) 
        {
            HttpClient client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"{Constants.baseurl}/songs/get-details?key={id}"),
                Headers =
                {
                    { "X-RapidAPI-Host", Constants.host },
                    { "X-RapidAPI-Key", Constants.extraApikey },
                },
            };
            TrackInfo result;
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var content = response.Content.ReadAsStringAsync().Result;
                result = JsonConvert.DeserializeObject<TrackInfo>(content);
            }            
            Track newItem;
            if (result.Sections[1].Text == null)
            {
                Uri uri = new Uri(result.Sections[1].Youtubeurl.Actions[0].Uri);
                string videoid = uri.Segments.Last();
                string videouri = $"https://www.youtube.com/embed/{videoid}";
                newItem = new(
                    result.Key, result.Title, result.Subtitle,
                    result.Images.Background, result.Images.Coverart,
                    result.Genres.Primary, "The track has no lyrics",
                    "So threre is no footer for lyrics",
                    result.Sections[1].Youtubeurl.Caption,
                    videouri
                );
            }
            else
            {
                Uri uri = new Uri(result.Sections[2].Youtubeurl.Actions[0].Uri);
                string videoid = uri.Segments.Last();
                string videouri = $"https://www.youtube.com/embed/{videoid}";
                string lyrics = string.Join(".", result.Sections[1].Text.ToArray()); ///////////
                newItem = new(
                    result.Key, result.Title, result.Subtitle,
                    result.Images.Background, result.Images.Coverart,
                    result.Genres.Primary, lyrics,
                    result.Sections[1].Footer,
                    result.Sections[2].Youtubeurl.Caption,
                    videouri
                );
            }
            return View(newItem);
        }       
    }
}

WebApplication1/Controllers/TracksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TracksController : Controller
    {
        private readonly WebApplication1Context _context;

        public TracksController(WebApplication1Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString)
        {            
            var tracks = from t in _context.Track
                 select t;

            if (!string.IsNullOrEmpty(searchString))
            {
                tracks = tracks.Where(s => s.Title!.Contains(searchString) || s.Subtitle!.Contains(searchString));
            }
            return View(await tracks.ToListAsync());             
        }

        public IActionResult Artists() 
        {
            var tracksDist = _context.Track
                .GroupBy(t => t.Subtitle)
                .Select(g => g.First())
                .ToList();

            Constants.tracksCount = _context.Track
                .GroupBy(t => t.Subtitle)
                .Select(g => g.Count())
                .ToList();

            return View(tracksDist);
        }
        
        public async Task<IActionResult> ArtistDetails(string id) 
        {
            var tracks = _context.Track.Where(s => s.Subtitle == id);
            return View(await tracks.ToListAsync());
        }

        public IActionResult Add(string Key, string Title, string Subtitle, string Background, string Coverart, string Genres, string Text, string Footer, string Caption, string Uri) 
        {
            Track track = new
                (
                    Key,
                    Title,
                    Subtitle,
                    Background,
                    Coverart,
                    Genres,
                    Text,
                    Footer,
                    Caption,
                    Uri
                );
            return View(track);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Key,Title,Subtitle,Background,Coverart,Genres,Text,Footer,Caption,Uri")] Track track) {
            if (ModelState.IsValid)
            {
                _context.Add(track);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(track);            
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Track == null)
            {
                return NotFound();
            }

            var track = await _context.Track
                .FirstOrDefaultAsync(m => m.Key == id);
            if (track == null)
            {
                return NotFound();
            }

            return View(track);
        }

        public async Task<IActionResult> GetLink(string id) {
            HttpClient client = new HttpClient();           
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"{Constants.baseurlDownload}/dl?id={id}"),
                Headers =
                {
                    { "X-RapidAPI-Host", Constants.hostDownload },
                    { "X-RapidAPI-Key", Constants.apikey },
                },
            };
            DownloadLink result;
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var content = response.Content.ReadAsStringAsync().Result;
                result = JsonConvert.DeserializeObject<DownloadLink>(content);
            }
            Process.Start(new ProcessStartInfo
            {
                FileName = result.Link,
                UseShellExecute = true
            });
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddToPlaylist(string id) {
            Constants.trackId = id;
            return View("~/Views/Playlists/Menu.cshtml", await _context.Playlist.ToListAsync());
        }     

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Track == null)
            {
                return NotFound();
            }

            var track = await _context.Track.FindAsync(id);
            if (track == null)
            {
                return NotFound();
            }
            return View(track);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Key,Title,Subtitle,Background,Coverart,Genres,Text,Footer,Caption,Uri")] Track track)
        {
            if (id != track.Key) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(track);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrackExists(track.Key)) return NotFound();
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(track);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Track == null) return NotFound();

            var track = await _context.Track
                .FirstOrDefaultAsync(m => m.Key == id);
            if (track == null) return NotFound();

            return View(track);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Track == null) return Problem("Entity set 'WebApplication1Context.Track'  is null.");

            var track = await _context.Track.FindAsync(id);
            if (track != null) _context.Track.Remove(track);

            var playlist = await _context.Playlist.FirstOrDefaultAsync(m => m.Id == track.PlaylistId);
            if (playlist != null)
            {
                if (playlist.TracksCount > 1)
                    playlist.TracksCount -= 1;
                playlist.TracksCount = 0;  
            }
                        
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }       
       
        private bool TrackExists(string id)
        {
          return _context.Track.Any(e => e.Key == id);
        }
       
    }
}

WebApplication1/Views/Search/Details.cshtml
@model WebApplication1.Models.Track

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Track</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Background)            
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Background" alt="Artist Image" width="230" height="230" style="border:3px solid white;"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Coverart)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Coverart" alt="Track Image" width="230" height="230" style="border:3px solid white;"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @{
                var lyrics = Model.Text.Split(".");
                foreach(string l in lyrics)
                {
                    <div>@l.ToString()</div>
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Footer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Footer)
        </dd>     
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Caption)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Caption)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Uri)
        </dt>
        <dd class = "col-sm-10">                 
            <iframe style="border:3px solid white;" loading="lazy" title="Music video" width="640" height="360" src="@Model.Uri" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </dd>
    </dl>
</div>
    <br />
<div>
    @{
        var newItem = new Dictionary<string, string>
            {
                {"Key", Model.Key },
                {"Title", Model.Title },
                {"Subtitle", Model.Subtitle },
                {"Background", Model.Background },
                {"Coverart", Model.Coverart },
                {"Genres", Model.Genres },
                {"Text", Model.Text },
                {"Footer", Model.Footer },
                {"Caption", Model.Caption },
                {"Uri", Model.Uri }
            };
    }
    <br />
    <a asp-controller="Tracks" asp-action="Add" asp-all-route-data="newItem">Add</a> | 
    <a asp-controller="Home" asp-action="Search">Back to Search</a>
</div>

WebApplication1/Views/Search/Index.cshtml
@model WebApplication1.Models.Shazam

@{
    ViewData["Title"] = "Search";
}

<h2>Enter the name of track</h2>
<form asp-controller="Search" asp-action="Index">
    <p>
        Name: <input type="text" name="SearchString" />
        <input type="submit" value="Search" />
    </p>
</form>
@if (Model != null)
{
<div class="form-horizontal">
    <hr />
    <div class="form-group">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Tracks.Hits.FirstOrDefault().Track.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tracks.Hits.FirstOrDefault().Track.Subtitle)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tracks.Hits.FirstOrDefault().Track.Share.Href)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tracks.Hits.FirstOrDefault().Track.Share.Image)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tracks.Hits.FirstOrDefault().Track.Share.Avatar)
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model.Tracks.Hits) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Track.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Track.Subtitle)
                    </td>
                    <td>
                         <a href="@item.Track.Share.Href">@item.Track.Share.Subject</a> 
                    </td>
                    <td>
                        <img src="@item.Track.Share.Image" alt="Track Image" width="230" height="230"/>
                    </td>
                    <td>
                        @if(item.Track.Share.Avatar == null)
                        {
                            <img src="@item.Track.Share.Image" alt="Artist Image" width="230" height="230"/>
                        }
                        else
                        {
                            <img src="@item.Track.Share.Avatar" alt="Artist Image" width="230" height="230"/>
                        }                        
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Track.Key">Details</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
}